# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyncu" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "76e40071ff74c22cb106b42226a5cb0e7365e926b9a5b9716aa03469a96503fe"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f205050f9f55b1d4da30e4601264c66d265a4307ac71513f8520f443c530eeb8"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2b10ab76dd829293b7e2c7a9f4517f169482ca251cb64224b644f8941955b76a"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "697ececd8341055739f8f7cce524bd917009032da0f7e546361c94075274e2c9"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lazyncu"
  desc "Read-only terminal dashboard for npm-check-updates"
  homepage "https://github.com/luchrv/lazyncu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyncu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyncu"]
    end
  end

  # No zap stanza required

end
