# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyncu" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "69839fc927c810a1553c0082782e0ddd38de6d1cd7ca1cc6e548684c7e7fc441"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2deff61583ae4a4f0cc1e3149522f246c943bc74800ac21b317cee07ae1be376"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8e39d04abee78b2b65cfa58bd77848cd517807b1dd66c5c67319297b33fdd1f3"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "32a50f8b09df537ccfe41b6279dec10e4bfb9ba95a523a210a786dca78328f5c"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lazyncu"
  desc "Read-only terminal dashboard for npm-check-updates"
  homepage "https://github.com/luchrv/lazyncu"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "npm-check-updates",
    ]

  binary "lazyncu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyncu"]
    end
  end

  # No zap stanza required

end
