# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyncu" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "ec70f0bac3ba952d3803126fe20fe55ce423c02d9246dcec9c98a79c66a93704"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f59513588a3bbe9eadd702372ebde47d65de2695d46ecbd1d69b3631a1b183c"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "11d3bf3d60934901a83c35f23085a2b240ac92ade2a4c97efd8c6f2dad3ca9a7"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4360bc1a9889850dfec571c1cae65a9715da59cf76b629cb5391b173047bcf5"
      url "https://github.com/luchrv/lazyncu/releases/download/v#{version}/lazyncu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lazyncu"
  desc "Read-only terminal dashboard for npm-check-updates"
  homepage "https://github.com/luchrv/lazyncu"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "npm-check-updates",
    ]

  binary "lazyncu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyncu"]
    end
  end

  # No zap stanza required

end
